library(readxl)
data<-read_excel("/Users/suhanisk/Desktop/wd/stats/fishstory.xls")
t_test<-t.test(data$`1980 Price`,data$`1970 Price`,paired = TRUE)
print(t_test)
cat("confidence interval:",t_test$conf.int[1],"to",t_test$conf.int[2])
mean_diff<-mean(data$`1980 Price`-data$`1970 Price`,na.rm=TRUE)
cat("mean difference bw 1980 price -1970 price:",mean_diff)
